version: '3'

networks:
  local_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24
          # gateway: 172.10.0.1
          # remove gateway from yml version 3

services:

  nginx_main:
    build: ./nginx/main
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt:/opt
      - /Users/hui/ch/projects:/workdir/projects
      - /Users/hui/ch/websites:/workdir/websites
    networks:
      local_net:
        ipv4_address: 172.10.0.11
    ports:
      - "80:80"
    hostname: local_nginx_main
    container_name: nginx_main

  php_main:
    build: ./php/main
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt:/opt
      - /Users/hui/ch/projects:/workdir/projects
      - /Users/hui/ch/websites:/workdir/websites
    networks:
      local_net:
        ipv4_address: 172.10.0.21
    ports:
      - "9001:9000"
    hostname: local_php_main
    container_name: php_main

  php_ext_v5:
    build: ./php/ext_v5
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt:/opt
      - /Users/hui/ch/projects:/workdir/projects
      - /Users/hui/ch/websites:/workdir/websites
      - /Users/hui/ch/projects/php-extensions/laosiji:/usr/src/php/ext/laosiji
    networks:
      local_net:
        ipv4_address: 172.10.0.22
    ports:
      - "9002:9000"
    hostname: local_php_ext_v5
    container_name: php_ext_v5

  php_ext_v7:
    build: ./php/ext_v7
    volumes:
      - ./common/hosts:/etc/hosts:ro
      - ./opt:/opt
      - /Users/hui/ch/projects:/workdir/projects
      - /Users/hui/ch/websites:/workdir/websites
      - /Users/hui/ch/projects/php-extensions/laosiji:/usr/src/php/ext/laosiji
    networks:
      local_net:
        ipv4_address: 172.10.0.23
    ports:
      - "9003:9000"
    hostname: local_php_ext_v7
    container_name: php_ext_v7

  mysql_common:
    build: ./mysql/common
    volumes:
      - /Users/hui/ch/datas/mysql/common/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.30
    ports:
      - "3310:3306"
    hostname: local_mysql_common
    container_name: mysql_common
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  mysql_main:
    build: ./mysql/main
    volumes:
      - /Users/hui/ch/datas/mysql/main/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.31
    ports:
      - "3311:3306"
    hostname: local_mysql_main
    container_name: mysql_main
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  mysql_master:
    build: ./mysql/master
    volumes:
      - /Users/hui/ch/datas/mysql/master/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.32
    ports:
      - "3312:3306"
    hostname: local_mysql_master
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  mysql_slave:
    build: ./mysql/slave
    volumes:
      - /Users/hui/ch/datas/mysql/slave/db:/var/lib/mysql
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.33
    ports:
      - "3313:3306"
    hostname: local_mysql_slave
    container_name: mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'

  redis_common:
    build: ./redis/common
    volumes:
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.40
    ports:
      - "6380:6379"
    hostname: local_redis_common
    container_name: redis_common

  redis_main:
    build: ./redis/main
    volumes:
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.41
    ports:
      - "6381:6379"
    hostname: local_redis_main
    container_name: redis_main

  php_zan:
    build: ./php/zan
    volumes:
      - ./common/hosts:/etc/hosts:ro
    networks:
      local_net:
        ipv4_address: 172.10.0.24
    ports:
      - "9004:9000"
      - "8030:8030"
    hostname: local_php_zan
    container_name: php_zan

